all:
  vars:
    tmp_root_password: tmp_passwd_G*xhLX]9k-Yq55q2
  hosts:
    iso:
      ansible_host: 192.168.0.57
      ansible_user: root
    chroot:
      ansible_host: 192.168.0.57
      ansible_user: root
      ansible_port: 2222
      ansible_password: "{{ tmp_root_password }}"